[package]
name = "examples-freertos-stm32"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[[bin]]
bench = false
name = "time"
path = "src/bin/time.rs"
test = false

[dependencies]
cortex-m = { version = "0.7.7", default-features = false, features = [
  "critical-section-single-core",
] }
cortex-m-rt = { version = "0.7.5", default-features = false }
examples-common = { path = "../common", default-features = false, features = [
  "alloc",
] }
panic-halt = { version = "1.0.0", default-features = false }
stm32f7xx-hal = { version = "0.8.0", default-features = false, features = [
  "rt",
  "stm32f767",
] }
veecle-freertos-integration = { version = "0.1.2", default-features = false, features = [
  "link-freertos",
  # SAFETY: we use the same prototype in `FreeRTOSConfig.h` as required by this feature.
  "unsafe-hooks-assert",
] }
veecle-os = { path = "../../veecle-os", default-features = false, features = [
  "osal-freertos",
] }
