[package]
name = "traces-serialization"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
assert_cmd = "2.1.1"
veecle-os = { path = "../../../../veecle-os", default-features = false, features = [
  "osal-std",
  "telemetry-enable",
] }

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
