version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directories:
      - "veecle-os-examples/*"
      - "docs/user-manual/crates/*"
      - "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
    ignore:
      # Embassy doesn't support heapless versions >=0.9.0.
      - dependency-name: "heapless"
        versions: [">=0.9.0"]

      # DEV-1037, updating requires API breaking changes.
      - dependency-name: "embedded-io"
        versions: [">=0.7.0"]
      - dependency-name: "embedded-io-adapters"
        versions: [">=0.7.0"]
      - dependency-name: "embedded-io-async"
        versions: [">=0.7.0"]
      # Broken optional-`serde`-dependency, waiting on 8.0.0 to fix it <https://github.com/oxibus/can-dbc/pull/51>
      - dependency-name: "can-dbc"
        versions: ["7.0.0"]
