[package]
name = "veecle-telemetry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Veecle OS telemetry"
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"
targets = []

[dependencies]
hex = { workspace = true, features = ["serde"] }
pin-project = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
veecle-osal-api = { workspace = true }
veecle-telemetry-macros = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
pretty_assertions = { workspace = true, features = ["std"] }
serial_test = { workspace = true }
test-case = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "time",
] }
veecle-osal-std = { workspace = true }
veecle-telemetry = { path = ".", features = ["enable", "std"] }

[features]
default = []
alloc = ["serde_json/alloc", "serde/alloc"]
# Enable collecting and exporting telemetry data, should only be set in the final binary crate.
enable = ["veecle-telemetry-macros/enable"]
std = ["alloc", "rand/thread_rng"]

[lints]
workspace = true
