[licenses]
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
]

[[licenses.exceptions]]
crate = "epaint_default_fonts"
allow = ["OFL-1.1", "Ubuntu-font-1.0"]

[[licenses.exceptions]]
crate = "unicode-ident"
allow = ["Unicode-DFS-2016"]

[[licenses.exceptions]]
crate = "slotmap"
allow = ["Zlib"]
