[package]
edition = "2024"
license = "Apache-2.0"
name = "getting-started"
publish = false
version = "0.0.0"

[workspace]

[dependencies]
veecle-os = { path = "../../../../veecle-os", default-features = false, features = ["osal-std"] }

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
