[package]
name = "getting-started"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
veecle-os = { path = "../../../../veecle-os", default-features = false, features = [
  "osal-std",
] }

[dev-dependencies]
assert_cmd = "2.1.1"
