[package]
edition = "2024"
license = "Apache-2.0"
name = "veecle-os-examples-freertos-stm32"
publish = false
version = "0.0.0"

[workspace]

[dependencies]
cortex-m = { version = "0.7.7", default-features = false, features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7.5", default-features = false }
panic-halt = { version = "1.0", default-features = false }
stm32f7xx-hal = { version = "0.8", default-features = false, features = ["rt", "stm32f767"] }
veecle-freertos-integration = { version = "0.1.1", default-features = false, features = [
  "link-freertos",
  # SAFETY: we use the same prototype in `FreeRTOSConfig.h` as required by this feature.
  "unsafe-hooks-assert",
] }
veecle-os = { path = "../../veecle-os", default-features = false, features = ["osal-freertos"] }
veecle-os-examples-common = { path = "../common", default-features = false, features = ["alloc"] }

[[bin]]
name = "time"
path = "src/bin/time.rs"
test = false
bench = false

[[bin]]
name = "basic"
path = "src/bin/basic.rs"
test = false
bench = false
