
# cargo-vet audits file

[[audits.macro_rules_attribute]]
who = "Wim Looman <wim.looman@veecle.io>"
criteria = "safe-to-run"
version = "0.2.2"
notes = "The crate consists of only re-exports and simple `macro_rules!`."

[[audits.macro_rules_attribute-proc_macro]]
who = "Wim Looman <wim.looman@veecle.io>"
criteria = "safe-to-run"
version = "0.2.2"
notes = "Very brief audit just to verify it doesn't do anything outside using proc-macro APIs."
