[package]
name = "generate-markdown-index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Markdown index generator for crates documentation"
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[package.metadata]
# This crate uses `#![forbid(unsafe_code)]`.
workspace-checks.miri = false

[dependencies]
anyhow = { workspace = true }
scraper = { workspace = true }
walkdir = { workspace = true }

[lints]
workspace = true
