[package]
description = "Veecle OS telemetry VS Code extension"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "veecle-telemetry-vscode-extension"
publish = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata]
# This crate uses `#![forbid(unsafe_code)]`.
workspace-checks.miri = false

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
eframe = { workspace = true, default-features = false, features = ["default_fonts", "glow", "persistence"] }
re_log = { workspace = true, features = ["setup"] }
serde = { workspace = true }
tsify = { workspace = true, features = ["js"] }
veecle-telemetry-ui = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
