# Shorten the path in the GitHub UI.
name: coverage.yaml

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  merge_group:

# Cancel jobs for previous commits in the same branch.
# On main `head_ref` is not available and `run_id` is always unique.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  llvm-cov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-rustup
        with:
          rust-toolchain-toml: rust-toolchain-nightly.toml
      - uses: ./.github/actions/setup-arm-gnu-toolchain
      - uses: ./.github/actions/setup-cmake
      - uses: ./.github/actions/setup-tools
        with:
          cargo-nextest: true
          cargo-llvm-cov: true
          just: true

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5
        with:
          cache-bin: "false"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - run: >
          just coverage
          --workspace
          --exclude=capicxx-someip-sys
          --exclude=someip-test-service
          --exclude=someip-test-service-macro
          --exclude=someip-test-service-sys
          --exclude=someip-test-service-tests
          --exclude=veecle-os-data-support-someip
          --exclude=veecle-os-data-support-someip-macros

      - uses: actions/upload-artifact@v5
        with:
          name: coverage
          path: |
            cov.json
            codecov.json
          retention-days: 1

  llvm-cov-someip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: ./.github/actions/setup-rustup
        with:
          rust-toolchain-toml: rust-toolchain-nightly.toml
      - uses: ./.github/actions/setup-arm-gnu-toolchain
      - uses: ./.github/actions/setup-cmake
      - uses: ./.github/actions/setup-tools
        with:
          cargo-nextest: true
          cargo-llvm-cov: true
          just: true

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5
        with:
          cache-bin: "false"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      # `someip` tests `cargo run` this binary internally, pre-build it so they don't timeout.
      - run: eval "$(cargo llvm-cov show-env --export-prefix)" && cargo build -p someip-test-service

      - run: >
          just coverage
          --package=capicxx-someip-sys
          --package=someip-test-service
          --package=someip-test-service-macro
          --package=someip-test-service-sys
          --package=someip-test-service-tests
          --package=veecle-os-data-support-someip
          --package=veecle-os-data-support-someip-macros

      - run: mv codecov.json codecov-someip.json

      - uses: actions/upload-artifact@v5
        with:
          name: coverage-someip
          path: codecov-someip.json
          retention-days: 1

  codecov-upload:
    runs-on: ubuntu-latest
    needs:
      - llvm-cov
      - llvm-cov-someip
    # Skip codecov upload for dependabot PRs (no access to secrets).
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/download-artifact@v7
        with:
          name: coverage

      - uses: actions/download-artifact@v7
        with:
          name: coverage-someip

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          disable_search: true
          files: codecov.json,codecov-someip.json
